---
- name: Configure php-expose off
  hosts: php-expose
  serial: 1
  become: yes
  become_user: root
  become_method: dzdo
  vars:
    file_dir: /etc/
  tasks:
    - name: Change the expose_php from on to off
      lineinfile:
        dest: /etc/php.ini
        regexp: '^expose_php ='
        line: 'expose_php = off'
      notify: restart apache

    - name: Ensure apache is restarted
      service: name=apache state=started

  handlers:
    - name: restart apache
      service: name=apache state=graceful
