---
- name: Check for running apache service
  hosts: yum-dev

  tasks:
    - name: Check if apache is running
      shell: ps aux | grep httpd | awk 'FNR==1 { print $9,$10,$11,$12,$13 }'
      register: status

    - debug: msg="{{ status.stdout }}"

      
